# WPP Configuration File
# Contains file paths, directory structures, and system configuration

[DIRECTORIES]
# Root directories for different operating systems
WPP_ROOT_DIR_POSIX = "/Users/steve/Work/WPP"
WPP_ROOT_DIR_WINDOWS = "\\\\SBS\\public\\qube\\iSite\\AutoBOSShelleyAngeAndSandra"

[INPUTS]
# Input file patterns and names
IRREGULAR_TRANSACTION_REFS_FILE = "001 GENERAL CREDITS CLIENTS WITHOUT IDENTS.xlsx"
PROPERTIES_FILE_PATTERN = "Properties*.xlsx"
TENANTS_FILE_PATTERN = "Tenants*.xlsx" 
ESTATES_FILE_PATTERN = "Estates*.xlsx"
QUBE_EOD_BALANCES_PATTERN = "Qube*EOD*.xlsx"
BANK_ACCOUNTS_PATTERN = "Accounts*.xlsx"
BOS_TRANSACTIONS_PATTERN = "PreviousDayTransactionExtract_*.zip"
BOS_BALANCES_PATTERN = "EndOfDayBalanceExtract_*.zip"

[REPORTS]
# Report file naming patterns
DATA_IMPORT_ISSUES_TEMPLATE = "Data_Import_Issues_{date}.xlsx"
WPP_REPORT_TEMPLATE = "WPP_Report_{date}.xlsx"

[LOGS]
# Log file names
REF_MATCHER_LOG = "ref_matcher.csv"
UPDATE_DATABASE_LOG = "update_database_{timestamp}.txt"
RUN_REPORTS_LOG = "run_reports_{timestamp}.txt"
# Enable/disable ref_matcher CSV logging (console apps and tests default to true, web apps default to false)
REF_MATCHER_CSV_ENABLED = false

[TENANT_REFERENCE_PARSING]
# Properties that require special handling for tenant references (4-digit patterns)
SPECIAL_CASE_PROPERTIES = ["138", "157"]
# Properties that exclude Z suffix tenant references
EXCLUDE_Z_SUFFIX_PROPERTIES = ["020", "022", "039"]
# Properties that use commercial (COM) block references
COMMERCIAL_PROPERTIES = ["099", "144", "156"]
# Properties that use industrial estate single-letter tenant references
INDUSTRIAL_ESTATE_PROPERTIES = ["177"]
# Properties that use digit-letter suffix tenant references (XXX-XX-DDDA format)
DIGIT_LETTER_SUFFIX_PROPERTIES = ["053", "059", "064", "133", "138", "142", "147", "148", "153", "157"]
# Properties that use digit-letter-digit tenant references (XXX-XX-0AD format)
LETTER_DIGIT_LETTER_PROPERTIES = ["094"]
# Properties that use 00X tenant references (XXX-XX-00A format)
DOUBLE_ZERO_LETTER_PROPERTIES = ["134", "154"]
# Properties that use three-letter code tenant references (XXX-XX-ABC format)
THREE_LETTER_CODE_PROPERTIES = ["094", "166"]
# Properties that use two-letter code tenant references (XXX-XX-AB format)
TWO_LETTER_CODE_PROPERTIES = ["161"]
# Properties that use alphanumeric property references (059A format)
ALPHANUMERIC_PROPERTIES = ["059A"]

[SERVER]
# Server monitoring and auto-shutdown settings
# Maximum runtime in minutes (set to 0 to disable auto-shutdown) - 2 hours
MAX_RUNTIME_MINUTES = 120
# Check interval for connection monitoring in seconds (ping interval)
CONNECTION_CHECK_INTERVAL = 10
# Delay before shutdown when no connections detected (minutes) - 20 minutes
NO_CONNECTION_SHUTDOWN_DELAY = 20